Update FinalResultController.php
portabilis/i-educar-reports-package pull request #91
Opened 2021-12-18 02:52 UTC by gilcimartec

2021-12-20 12:03 UTC, edersoares requested changes

2021-12-20 12:03 UTC, edersoares commented on ieducar/Views/FinalResultController.php
> +        $this->report->addArg('portaria_aprovacao_pontos', Portabilis_String_Utils::toUtf8((string) $GLOBALS['coreExt']['Config']->report->portaria_aprovacao_pontos));
O método `Portabilis_String_Utils::toUtf8` retorna a própria string e pode ser removido.

```suggestion
        $this->report->addArg('criterio_aprovacao', (string) $this->getRequest()->criterio_aprovacao);
        $this->report->addArg('portaria_aprovacao_pontos', (string) $GLOBALS['coreExt']['Config']->report->portaria_aprovacao_pontos);
```

2021-12-20 12:04 UTC, edersoares commented
@gilcimartec é bom colocar uma descrição do motivo da alteração.

2021-12-23 22:11 UTC, gilcimartec commented on ieducar/Views/FinalResultController.php
> +        $this->report->addArg('portaria_aprovacao_pontos', Portabilis_String_Utils::toUtf8((string) $GLOBALS['coreExt']['Config']->report->portaria_aprovacao_pontos));
Obrigado @edersoares

2021-12-23 22:19 UTC, gilcimartec commented
Com essa modificação o relatório de resultado final irá abrir nas recentes versões do i-Educar.

2021-12-23 22:24 UTC, gilcimartec reviewed
Obrigado

2021-12-23 22:40 UTC, gilcimartec commented
Parece que fiz bagunça. Desculpa. Novato em github.

2021-12-23 22:40 UTC, gilcimartec commented
Parece que fiz bagunça. Desculpa. Novato em github.

2021-12-27 19:21 UTC, edersoares commented
Tranquilo @gilcimartec 😄, só fazer o ajuste conforme o code review.

2021-12-28 12:12 UTC, gilcimartec reviewed
Obrigado pelas mudanças.

2021-12-28 12:12 UTC, gilcimartec commented on ieducar/Views/FinalResultController.php
> +        $this->report->addArg('criterio_aprovacao', (string) $this->getRequest()->criterio_aprovacao);
Ok. Revisado.

2021-12-28 12:12 UTC, gilcimartec commented on ieducar/Views/FinalResultController.php
> +        $this->report->addArg('portaria_aprovacao_pontos', (string) $GLOBALS['coreExt']['Config']->report->portaria_aprovacao_pontos);
Ok. Revisado.

2021-12-28 12:22 UTC, edersoares approved these changes

2021-12-28 12:22 UTC, edersoares commented
Obrigado @gilcimartec.

2021-12-28 12:22 UTC, merged